### PR TITLE
Update snapcraft.yaml

### PR DESCRIPTION
**Pull request by Pilzinsel64**

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
@kyrofa Looks like you need to approve once as I never PRed to this repo.

**Comment by kyrofa** [comment]
Gah, same failure: https://github.com/kyrofa/ignore-me/actions/runs/6277364903/job/17048939042 . Stupid github. I'll need to figure out another way to get the PR number. Thank you @Pilzinsel64, this was helpful. If you can figure out how to use the github API to turn this workflow run into a pull request ID, let me know. I'll investigate as well.

**Comment by Pilzinsel64** [comment]
Sure, I will let you know!

**Comment by Pilzinsel64** [comment]
@kyrofa something like this, maybe?
https://github.com/actions/checkout/issues/58#issuecomment-545446510
Just a quick search, will search more...

**Comment by Pilzinsel64** [comment]
Or maybe this via the gh tool:
https://github.com/actions/checkout/issues/58#issuecomment-1190882933

**Comment by kyrofa** [comment]
Yeah we're not using the pull request event, but the [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) event, which has different data available.

**Comment by Pilzinsel64** [comment]
Ah, I see.

**Comment by Pilzinsel64** [comment]
Looks like this is a topic nobody talked about. Maybe I can get little into the API documentation this day.

And alrernive would be to rename the snap.snap to snap_prid.snap? This however would still enable thepr owner to push a  custom pr Id?
However, for first contributed you need to approve the test even, so, bot sure if protecting the PR is is needed that quickly (at least for now, until we find a better solution).

**Comment by Pilzinsel64** [comment]
Hm, this sounds definetly like our problem. What do you think @kyrofa? 🤔 But looks like the solution is the same again, upload it as artifact.
https://github.com/orgs/community/discussions/25220#discussioncomment-3246922

**Comment by pachulo** [comment]
The problem is, again, that the PR author has control over which channel
the snap will be pushed to. :sad:

And what about the workaround commented here @kyrofa?
https://github.com/orgs/community/discussions/25220#discussioncomment-3246923

Even though the https://github.com/marketplace/actions/get-workflow-origin
uses a "brute force" approach, it should be OK from a security point of
view, shouldn't it?

El dg., 24 de set. 2023, 11:04, Pilzinsel64 ***@***.***> va
escriure:

**Comment by kyrofa** [comment]
Haha, I read @Pilzinsel64's link and came to say the same thing as @pachulo. Yes, exactly. That approach sounds promising indeed, I'll give it a shot. Good work, guys!

**Comment by kyrofa** [comment]
@Pilzinsel64 okay try rebasing on master.

**Comment by Pilzinsel64** [comment]
Oh, you got it? The error now is at least about the snap file being corrupted.

**Comment by kyrofa** [comment]
Yeah this is definitely promising, but I'm not sure what's happening now.

**Comment by Pilzinsel64** [comment]
Maybe I should edit something else. Give me a sec...

**Comment by kyrofa** [comment]
No I found it, re-open. Then I can fix it. You need to rebase on my `change` branch, it's the one that actually builds a snap.

**Comment by Pilzinsel64** [comment]
Oh, sorry, see #4
Hope that's fine.

**Pull request closed without merging**
